import Header from '@/compomemts/layout/Header'
import './globals.css'

export const metadata = {
  title: 'Panaverse',
  description: 'Generated by M.Sami Ansari',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg'>
        
      {/* header */}
      <Header/>
        {children}</body>
    </html>
  )
}
